spring.application.name=demo
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:shipdb
spring.datasource.username=sa
spring.jpa.hibernate.ddl-auto=update

# JobRunr Config
org.jobrunr.background-job-server.enabled=true
org.jobrunr.dashboard.enabled=true
org.jobrunr.dashboard.port=8000
